apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
      - name: phpldapadmin
        image: osixia/phpldapadmin:0.9.0
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: "openldap"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
spec:
  selector:
    app: phpldapadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
